### ISSUE TITLE
Path from *_rvalid_i to performance counter

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/cv32e40p#371]
Combinatorial paths exist from the *_rvalid_i inputs to mhpmcounter_q[3]. The rvalid signals are typically late arriving inputs the the stated performance counter uses a 64-bit incrementer.

Would it be okay to count all events 1 cycle later (thereby preventing the performance counters from contributing to critical paths)?

**Comment by MikeOpenHWGroup** [comment]
Its "probably" OK, as long as its documented in the user manual.  Verificiation does not yet have a Vplan captured for performance counters, so I do not know if we will need to check these on-the-fly or at the end-of-sim.  If its end-of-sim, then this change will not impact verification.  If we need on-the-fly, then the TB will need to "know" this.

**Comment by davideschiavone** [comment]
I think the error is here:
```

        if( cnt_idx == 0)
          // mcycle = mhpmcounter[0] : count every cycle (if not inhibited)
          mhpmcounter_n[cnt_idx] = **mhpmcounter_n**[cnt_idx] + 1;

        else if(cnt_idx == 2)
          // minstret = mhpmcounter[2]  : count every retired instruction (if not inhibited)
          mhpmcounter_n[cnt_idx] = **mhpmcounter_n**[cnt_idx] + hpm_events[1];

        else if( (cnt_idx>2) && (cnt_idx<(NUM_MHPMCOUNTERS+3)))
          // add +1 if any event is enabled and active
          mhpmcounter_n[cnt_idx] = mhpmcounter_q[cnt_idx] +
                                   |(hpm_events & mhpmevent_q[cnt_idx][NUM_HPM_EVENTS-1:0]) ;
```

it should be  

mhpmcounter_n[cnt_idx] = **mhpmcounter_q**[cnt_idx] + 1;

mhpmcounter_n[cnt_idx] = **mhpmcounter_q**[cnt_idx] + hpm_events[1];

Can you please fix it ? @silabs-PaulZ

**Comment by davideschiavone** [comment]
I reopened the issue as this should be first checked with synthesis, for the moment I fixed that typo

**Comment by Silabs-ArjanB** [comment]
I will run a synthesis to check; thanks!

**Comment by Silabs-ArjanB** [comment]
The combinatorial paths still exist, but the unwanted long paths are gone, so the fix looks good. (Fixing the combinatorial path all together would most likely involve changing the cv32e40p_controller, which is not considered worth the effort)
